package com.hfh9527.demo.core_jobtop;

import java.util.List;

public class DataInitService {
	
	public void initJobAndCondationsByData(BatJobsAndConds jcs) {
		initJobBeginByData(jcs.batJobsBegin);
		initJobMiddleByData(jcs.batJobsMiddle);
		initJobEndByData(jcs.batJobsEnd);
		initCondationsByData(jcs.condAll);
		
		intCond(jcs.condAll, jcs.condBegin, 1);
		intCond(jcs.condAll, jcs.condMiddle, 2);
		intCond(jcs.condAll, jcs.condEnd, 3);
		
		System.out.println(jcs.batJobsBegin.size() + ":" +  jcs.condBegin.size());
		System.out.println(jcs.batJobsMiddle.size() + ":" +  jcs.condMiddle.size());
		System.out.println(jcs.batJobsEnd.size() + ":" +  jcs.condEnd.size());
	}

	private void intCond(List<BatJobCond> condAll, List<BatJobCond> condBegin,
			int projectCode) {
		for (BatJobCond cond : condAll) {
			if( cond.projectCode == projectCode){
				condBegin.add(cond);
			}
		}
	}

	void initJobBeginByData(List<BatJob> batJobsBegin) {
		BatJob batJob = null;
		batJob = new BatJob(1, 5, 10, "����Ϣ�������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 5, 20, "�����Ϣ�������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 5, 25, "�ڲ��˿�Ϣ�������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 5, 26, "��������˿�Ϣ�������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 5, 27, "����ʽ����Զ��ۿ�?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 5, 28, "����ʽ�����Ϣ����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 5, 29, "����ʽ���ֹͣ�ۿ����֪ͨ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 5, 30, "��Ϣ�������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 10, 5, "�������������ʼ��?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 20, 5, "��ͨ������ս�Ϣ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 21, 5, "�޷�Խ���������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 30, 5, "��ͨ������տۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 40, 5, "��ͨ������̬ת��");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 41, 5, "��ͨ���ڴ���������Ϣ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 42, 5, "��ͨ���ڴ��������ۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 50, 5, "�ֳ�����������Ϣ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 60, 5, "�ֳ����������ۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 60, 10, "����֤������Ϣ�ۿ���ڿۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 70, 5, "ת����������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 80, 6, "�����ʽ����Զ�ת��");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 90, 6, "������ڴ���?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 100, 6, "�ʽ��������嵥");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 109, 6, "�Żݽ���������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 110, 6, "��һ��������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 120, 6, "Ӫҵ˰���Զ���ת");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 130, 2, "���ǿ��Կۻ���");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 131, 2, "���ǿ����ղ���");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 140, 4, "�жһ�Ʊ���ڿۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 140, 5, "���ӳжһ�Ʊ���ڿۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 149, 2, "�������˻�������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 150, 2, "�����ڵ��ڻ�����");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 160, 2, "��������ʻ��黹����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 180, 2, "����ʻ�ת����������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 190, 2, "��Լ��ת��");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 200, 1, "���ԤԼת��?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 210, 1, "����Զ�ת��?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 215, 2, "���Զ�ת����ϸ����");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 220, 1, "����������������ѻ�ת����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 225, 2, "Ԥ��Ȩ������������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 230, 1, "����ҵ��������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 240, 1, "����֪ͨ����");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 245, 1, "�����ʻ��Զ����ۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 255, 7, "�ϱ��������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 260, 7, "ǰ�嵥������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 270, 6, "ҵ����������");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 280, 6, "�ƿ���ӡ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 292, 6, "Ӫҵ˰���Զ�����");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 295, 6, "�����Ŀ���?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 296, 1, "�����֧�����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 297, 1, "�ɶ��������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 298, 4, "С���ǵ����嵥��ӡ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 299, 1, "С������δǩԼ�嵥��ӡ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 300, 1, "ֽƱ�ǼǴ���");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 305, 7, "��Ϣ˰����");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 305, 8, "�籣ί�пۿ����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 306, 5, "����ƾ֤�����ϼ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 307, 2, "����ѭ���������������?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 308, 2, "����ѭ�����������ۿ�");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 309, 6, "���������Ա��Ϣ�?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 309, 8, "�ƽ�ҵ�����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 309, 9, "���ڹ�����");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 309, 20, "����֧�����м��?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 311, 1, "���������ʽ����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 313, 1, "�����˻��ÿ�ƻ�����ת����?");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 320, 1, "��Ժ���綳�Ṥǰ��ӡ");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 400, 2, "ת��POS�Żݼ���");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 401, 2, "��������binά��");
		batJobsBegin.add(batJob);
		batJob = new BatJob(1, 701, 9, "��Ϣ�Զ�ת��֪ͨ���?");
		batJobsBegin.add(batJob);
	}

	void initJobMiddleByData(List<BatJob> batJobsMiddle) {
		BatJob batJob = null;
		batJob = new BatJob(2, 1, 1, "����Ǽǲ�����?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 105, 1, "���ֶһ�������ϸ����");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 132, 2, "���ɴ��ǿ�����");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 300, 1, "�����ʻ�͸֧����");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 310, 1, "���һ��ͨ͸֧�ſ�?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 315, 4, "�����Զ�����");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 325, 6, "�編�������ʽ�תͬҵ");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 330, 6, "�����ʽ�͸֧�黹");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 340, 6, "�����ʽ�͸֧���?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 350, 6, "����ƽ�����Զ�����");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 351, 6, "����������");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 352, 6, "������?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 356, 4, "ͨ��ͨ���嵥");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 357, 4, "���������ܿ�Ŀ�嵥");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 360, 6, "��������");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 390, 6, "��Ŀ������ϵ���?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 400, 6, "�Զ����Ҽ��?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 410, 6, "����ƽ����");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 411, 9, "������Ȩ��ˮ");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 412, 9, "�������⽻����ˮ");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 413, 9, "�������ʵ�������");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 420, 6, "�ּܷ��?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 421, 6, "��������");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 430, 6, "����������ˮ");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 432, 5, "�Ŵ�ж��");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 433, 1, "���������ӡ���ʵ�?");
		batJobsMiddle.add(batJob);
		batJob = new BatJob(2, 502, 5, "�����ж��");
		batJobsMiddle.add(batJob);
	}

	void initJobEndByData(List<BatJob> batJobsEnd) {
		BatJob batJob = null;
		batJob = new BatJob(3, 298, 1, "��Ʋ�Ʒ���ڿۿ�?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 299, 2, "��Ʊ�Թ��˻���Ϣж��");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 434, 6, "�����Ա������ձ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 435, 6, "���Ᵽ֤���յ�����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 495, 10, "����Ϣ�������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 495, 20, "�����Ϣ�������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 495, 25, "�ڲ��˿�Ϣ�������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 495, 26, "��������˿�Ϣ�������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 495, 30, "��Ϣ�������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 496, 26, "��������˹鼯��������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 500, 6, "���ܱ�������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 501, 1, "VIP�ͻ���ѯ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 503, 4, "�Ͼ�����˰�ѽ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 503, 5, "���ڴ���˰�ѽ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 503, 6, "��Ϫ����ˮ�ѽ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 503, 7, "��������ˮ�ѽ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 505, 6, "��Ա��Ŀ�ռǱ�");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 510, 6, "����ƽ���?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 520, 1, "������ϸ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 530, 6, "�ʲ���ծ��");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 532, 5, "�Ŵ�ж��֮�������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 540, 6, "�ڲ��ʽ�Ϣ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 550, 6, "�ڲ�������ϸ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 560, 6, "�ڲ������ʵ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 570, 6, "�ڲ������մ�ӡ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 580, 6, "�ڲ�����������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 590, 5, "��ͨ����������Ϣ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 600, 5, "��ͨ���������ۿ�");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 600, 90, "��ͨ����ת�ֳ�");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 610, 5, "�����������ʵ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 620, 5, "��ͨ����������ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 630, 5, "�ֳ�����������ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 635, 5, "����������ϢԤ�㴦��");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 638, 5, "����������ϢԤ����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 640, 5, "������������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 645, 5, "����ƽ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 645, 10, "Ƿ�����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 645, 15, "����֤������Ϣ�ۿ���ڿۿ�Ԥ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 645, 20, "����֤������Ϣ�ۿ���ڿۿ�");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 650, 4, "���гжһ�Ʊ�嵥��ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 660, 4, "�����嵥��ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 670, 4, "���������շ�");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 690, 4, "����Ǽǲ�����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 691, 4, "��������ϵͳ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 700, 2, "ATM��CDM������ˮ�嵥");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 720, 2, "��ҵ����Ϣͳ��");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 721, 2, "��������ͨ����ת����ˮ��ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 722, 6, "ϵͳ�ڶ����ʽ�֧ȡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 723, 6, "һ����׼���𼰱��������ʷֶδ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 730, 1, "���������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 740, 2, "˯�߿�����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 775, 2, "���������޸�");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 778, 2, "���п���ϸ��ˮ,������ˮ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 779, 2, "�������ձ�ͳ��");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 790, 1, "�����ϸ����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 810, 1, "���ͳ��?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 815, 1, "ͬҵ���ڽ�Ϣ������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 816, 1, "�Զ�ת����Ϣ�ص���ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 820, 1, "��Ϣ˰�嵥�ͱ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 830, 1, "˯�߻������Զ����ء�ת����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 835, 1, "�Թ��ֶ���Ϣ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 835, 2, "��˽��Ϣ˰�����ֶδ���");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 840, 1, "�Թ����Ƚ�Ϣ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 850, 1, "��˽���Ƚ�Ϣ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 851, 2, "����Ϣ��ϸ����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 860, 1, "��ɫ��Ϣ����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 870, 7, "���嵥������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 880, 7, "�������?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 888, 8, "ϵͳ��������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 890, 9, "����ֽ��ȡԤԼ�Զ�����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 900, 9, "��֤��ʧЭ���Զ����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 930, 1, "�Թ��ʻ�ж��");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 935, 6, "�ɴ���׼����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 940, 5, "���ͻ������ͳ�����");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 950, 8, "�ֽ����ԤԼ�Զ�����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 951, 8, "NC��Ŀ����ж��");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 963, 9, "����֪ͨ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 964, 9, "�����������пͻ�");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 970, 6, "������Ŀ�����嵥");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 980, 6, "�����?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 990, 5, "��������������");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 991, 4, "С��ڽ�ǵ��������ۿ�?");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 992, 7, "Զ�ڽ��ۻ��嵥��ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 993, 7, "�����������ҵ���ӡ");
		batJobsEnd.add(batJob);
		batJob = new BatJob(3, 996, 9, "�����ص�ж��");

	}

	void initCondationsByData(List<BatJobCond> batJobConds)
	{
		BatJobCond batJobCond = null;
		batJobCond = new BatJobCond (1, 305, 7, 109, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 255, 7, 20, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 255, 7, 30, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 255, 7, 41, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 255, 7, 42, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 255, 7, 50, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 255, 7, 60, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 645, 20, 645, 10);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 645, 15, 645, 10);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 41, 5, 60, 10);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 41, 5, 308, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 701, 9, 130, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 996, 9, 790, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 963, 9, 640, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 540, 6, 495, 30);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 996, 9, 850, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 298, 1, 645, 10);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 816, 1, 815, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 292, 6, 5, 30);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 25, 5, 20);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 495, 25, 495, 20);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 935, 6, 495, 30);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 20, 5, 10, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 30, 5, 20, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 40, 5, 30, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 50, 5, 10, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 60, 5, 50, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 70, 5, 60, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 100, 6, 90, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 100, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 200, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 210, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 20, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 40, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 50, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 80, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 90, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 180, 2, 190, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 215, 2, 210, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 210, 1, 150, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 220, 1, 210, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 230, 1, 225, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 240, 1, 220, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 245, 1, 240, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 260, 7, 250, 7);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 291, 6, 290, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 291, 6, 200, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 291, 6, 210, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 292, 6, 120, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 292, 6, 293, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 293, 6, 291, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 292, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 210, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 200, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 10, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 20, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 30, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 40, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 50, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 60, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 330, 6, 300, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 330, 6, 310, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 330, 6, 320, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 340, 6, 330, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 350, 6, 340, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 351, 6, 350, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 352, 6, 351, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 353, 6, 352, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 360, 6, 353, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 370, 6, 350, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 390, 6, 360, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 400, 6, 360, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 410, 6, 360, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 420, 6, 360, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 505, 6, 500, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 510, 6, 500, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 520, 6, 500, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 530, 6, 500, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 550, 6, 540, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 495, 25, 560, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 570, 6, 560, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 580, 6, 570, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 590, 5, 840, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 600, 5, 590, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 610, 5, 600, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 620, 5, 610, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 630, 5, 620, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 635, 5, 620, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 638, 5, 635, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 640, 5, 630, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 645, 5, 640, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 790, 1, 780, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 820, 1, 810, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 835, 1, 790, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 840, 1, 835, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 850, 1, 840, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 851, 2, 850, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 860, 7, 855, 7);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 870, 7, 860, 7);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 880, 7, 870, 7);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 292, 6, 110, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 650, 4, 670, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 660, 4, 670, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 690, 4, 650, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 690, 4, 660, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 986, 1, 985, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 985, 6, 810, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 990, 5, 640, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 150, 2, 149, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 600, 90, 600, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 20, 5, 21, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 41, 5, 40, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 42, 5, 41, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 600, 5, 840, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 600, 5, 850, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 41, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 42, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 41, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 295, 6, 42, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 961, 9, 640, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 840, 1, 810, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 850, 1, 810, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 290, 1, 30, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 290, 1, 42, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 290, 1, 60, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 290, 1, 140, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 290, 1, 220, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 640, 5, 985, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 432, 5, 431, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 421, 6, 420, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 431, 6, 430, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 590, 5, 502, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 835, 2, 835, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 210, 2, 150, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 149, 2, 230, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 722, 6, 935, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 110, 6, 260, 7);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 260, 7, 305, 7);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 120, 6, 305, 7);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 985, 6, 502, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 495, 20, 495, 10);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 495, 30, 495, 26);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 840, 1, 495, 30);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 850, 1, 495, 30);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 815, 1, 495, 30);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 20, 5, 10);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 30, 5, 26);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 40, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 645, 10, 645, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 30, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 60, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 140, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 190, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 200, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 210, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 308, 2, 30, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 250, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 250, 1, 245, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 330, 6, 325, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 325, 6, 300, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 325, 6, 310, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (2, 325, 6, 315, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 730, 1, 690, 4);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 110, 6, 109, 6);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 26, 5, 25);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 495, 26, 495, 25);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 28, 5, 27);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 701, 9, 5, 28);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 10, 701, 9);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 200, 1, 5, 28);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 190, 2, 5, 28);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 296, 1, 5, 27);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 29, 5, 28);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 27, 42, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 5, 27, 130, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (1, 130, 2, 308, 2);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 590, 5, 850, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 963, 9, 635, 5);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 860, 1, 850, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 860, 1, 810, 1);
		batJobConds.add( batJobCond );
		batJobCond = new BatJobCond (3, 860, 1, 495, 30);
		batJobConds.add( batJobCond );

	}

	
}
